# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f7b8f089a9ad6436c4701ad86a3774fca813654e0eea05f7a26732eb1ef4f01cb035a63e9bb79f5ef81109849980dd9b456ab156994b553c932c3a92d0f4bf7

test:
  secret_key_base: f45decb39d475c926254b65a7d8454bf9564a66699b05afaab2cab068a5ae8efa51d05a282f52c1a621f2e39bb3d956353084d61c8ea6ec721950c4966322e4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
